apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - networkpolicies.yaml
  - ingress.yaml
  - products.yaml
  - users.yaml
  - inventory.yaml
  - orders.yaml
  - payments.yaml
  - mysql.yaml
  - redis.yaml
  - mongo.yaml
  - storefront-deployment.yaml
  - storefront-service.yaml