apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    app: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: 361769595099.dkr.ecr.us-east-1.amazonaws.com/ecommerce-orders:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_DB
              value: "shop"
            - name: MYSQL_USER
              value: "shop"
            - name: MYSQL_PASSWORD
              value: "shop"

            - name: PAYMENTS_SERVICE_URL
              value: "http://payments-service:8003"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"

            - name: SPRING_DATASOURCE_USERNAME
              value: "shop"

            - name: SPRING_DATASOURCE_PASSWORD
              value: "shop"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders
spec:
  selector:
    app: orders
  ports:
    - port: 8084
      targetPort: 8080
  type: ClusterIP