apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    app: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: 361769595099.dkr.ecr.us-east-1.amazonaws.com/ecommerce-orders:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: ${{ vars.MYSQL_HOST }}
            - name: MYSQL_DB
              value: ${{ vars.MYSQL_DB }}
            - name: MYSQL_USER
              value: ${{ secrets.MYSQL_USER }}
            - name: MYSQL_PASSWORD
              value: ${{ secrets.MYSQL_PASSWORD }}

            - name: PAYMENTS_SERVICE_URL
              value: "http://payments-service:8003"

            - name: PAYMENT_BASE_URL
              value: "http://payments-service:8003"

            - name: USERS_BASE_URL
              value: "http://users-service:8083"

            - name: SPRING_DATASOURCE_URL
              value: ${{ vars.SPRING_DATASOURCE_URL }}

            - name: SPRING_DATASOURCE_USERNAME
              value: ${{ secrets.SPRING_DATASOURCE_USERNAME }}

            - name: SPRING_DATASOURCE_PASSWORD
              value: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

            - name: INVENTORY_BASE_URL
              value: "http://inventory-service:8002"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders
spec:
  selector:
    app: orders
  ports:
    - port: 8084
      targetPort: 8080
  type: ClusterIP