apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    app: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: 361769595099.dkr.ecr.us-east-1.amazonaws.com/ecommerce-orders:latest
          ports:
            - containerPort: 8080
          env:
            # DB: from ConfigMap
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: shop-config
                  key: MYSQL_HOST
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: shop-config
                  key: MYSQL_DB

            # DB credentials: from Secret
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_PASSWORD

            # Other service URLs
            - name: INVENTORY_BASE_URL
              value: "http://inventory-service:8002"
            - name: PAYMENT_BASE_URL
              value: "http://payments-service:8003"
            - name: USERS_BASE_URL
              value: "http://users-service:8083"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: shop
  labels:
    app: orders
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"   # container port where Spring Boot exposes actuator
spec:
  selector:
    app: orders
  ports:
    - name: http
      port: 8084          # Service (cluster) port
      targetPort: 8080    # forwards to containerPort (likely 8080)
  type: ClusterIP