apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders-metrics
  namespace: monitoring
  labels:
    release: ecommerce-monitoring   
spec:
  namespaceSelector:
    matchNames:
      - shop
  selector:
    matchLabels:
      app: orders                  
  endpoints:
    - port: http                  
      path: /actuator/prometheus
      interval: 15s
